Criação da Tipagem para ser usando com projetos em Typescript
jonathasbsouza/react-br-bank-icons pull request #10
Opened 2021-03-10 14:17 UTC by SergioVago

2021-03-22 14:56 UTC, caiobsouza requested changes

2021-03-22 14:56 UTC, caiobsouza commented on index.d.ts
> +}
Apenas faltando uma linha no EOF. Fora isso, LGTM. (y)

2021-03-24 12:29 UTC, SergioVago commented on index.d.ts
> +}
Adicionei os dois EOF

2021-03-24 20:00 UTC, caiobsouza approved these changes
LGTM! Obrigado por contribuir!

2021-03-24 20:00 UTC, merged